stages:
  - build
  - test

build:
  stage: build
  script:
    - cd /Users/antec/Desktop/quizwebapp/Quizwebapp
    - ./gradlew assemble
    - ./gradlew sonarqube

test:
  stage: test
  script:
    - cd /Users/antec/Desktop/quizwebapp/Quizwebapp
    - ./gradlew test