stages:
  - build
  - test

build:
  stage: build
  script:
    - cd ..
    - cd ..
    - cd ..
    - cd ..
    - cd ..
    - cd ..
    - cd Users
    - cd antec
    - cd Desktop
    - cd quizwebapp
    - cd QuizWebapp
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test